global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'node'
    ec2_sd_configs:
      - region: us-east-1
        port: 9100
  - job_name: 'jenkins'
    metrics_path: /prometheus/
    static_configs:
      - targets: [172.31.84.209:8080]